name: flexio_kvl
description: An application to see peak consumption in the MyFlexio App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^2.1.0
  icapps_architecture: ^0.8.1
  sprintf: ^7.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.4
  locale_gen: ^11.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/locale/